[package]
name = "markhangeul-web"
version = "0.1.0"
description = "Yew/WebAssembly playground for MarkHangeul."
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
markhangeul-core = { path = "../markhangeul-core" }
pulldown-cmark.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Element", "HtmlTextAreaElement", "HtmlInputElement", "HtmlSelectElement"] }
yew.workspace = true
unicode-segmentation.workspace = true
