[package]
name = "markhangeul-web"
version = "0.1.0"
description = "Yew/WebAssembly playground for MarkHangeul."
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
markhangeul-core = { path = "../markhangeul-core" }
serde_json.workspace = true
web-sys = { workspace = true, features = ["HtmlTextAreaElement"] }
yew.workspace = true
